#!/usr/bin/env sh
. "$(dirname -- "$0")/_/hook.sh"

deno task doc && deno run --allow-read --allow-env --allow-run --allow-write https://pax.deno.dev/kawarimidoll/deno-dev-template/scripts/lint-staged.ts
